import type { CPI, ThreatAssessment, OpsecIndicator, Countermeasure } from './types';

export const MOCK_CPIS: CPI[] = [
  {
    id: 'cpi-001',
    programName: 'GUARDIAN',
    cpiName: 'Advanced Propulsion System — Drive Configuration',
    description: 'Classified drive geometry and fuel-injection sequencing specs for the GUARDIAN propulsion subsystem.',
    classificationLevel: 'TOP SECRET',
    category: 'Technology',
    protectionStatus: 'Protected',
    owner: 'J. Hartwell',
    lastReviewDate: '2026-03-15',
    nextReviewDate: '2026-09-15',
    notes: 'DCSA reviewed. No deviations noted.',
  },
  {
    id: 'cpi-002',
    programName: 'CIPHER',
    cpiName: 'Quantum Key Distribution Algorithm',
    description: 'QKD implementation details and key-rotation schedule for CIPHER communications layer.',
    classificationLevel: 'TS/SCI',
    category: 'Methodology',
    protectionStatus: 'Under Review',
    owner: 'S. Nakamura',
    lastReviewDate: '2026-01-08',
    nextReviewDate: '2026-07-08',
    notes: 'Pending annual review — contractor access roster not yet reconciled.',
  },
  {
    id: 'cpi-003',
    programName: 'NIGHTWATCH',
    cpiName: 'Personnel Deployment Schedule — Phase II',
    description: 'Rotation timelines and assignment locations for NIGHTWATCH field personnel during Phase II operations.',
    classificationLevel: 'SECRET',
    category: 'Operations',
    protectionStatus: 'At-Risk',
    owner: 'M. Okafor',
    lastReviewDate: '2026-02-20',
    nextReviewDate: '2026-05-20',
    notes: 'OPSEC indicator flagged: schedule details partially observable via contractor travel vouchers.',
  },
  {
    id: 'cpi-004',
    programName: 'PRISM-7',
    cpiName: 'SIGINT Collection Methodology — Waveform Signatures',
    description: 'Specific waveform parameters and collection geometries used in PRISM-7 SIGINT operations.',
    classificationLevel: 'TS/SCI',
    category: 'Methodology',
    protectionStatus: 'Protected',
    owner: 'A. Torres',
    lastReviewDate: '2026-04-01',
    nextReviewDate: '2026-10-01',
    notes: 'Compartmented handling required. Limited to SCI-cleared analysts only.',
  },
  {
    id: 'cpi-005',
    programName: 'STARGATE',
    cpiName: 'Classified Network Architecture — Zone B',
    description: 'Network topology, node identifiers, and COMSEC plan for STARGATE classified enclave.',
    classificationLevel: 'SECRET',
    category: 'Infrastructure',
    protectionStatus: 'Protected',
    owner: 'R. Pham',
    lastReviewDate: '2026-03-28',
    nextReviewDate: '2026-09-28',
    notes: '',
  },
];

export const MOCK_THREATS: ThreatAssessment[] = [
  {
    id: 'threat-001',
    cpiId: 'cpi-001',
    threatActor: 'Foreign State-Sponsored Actor (Tier 1)',
    threatCategory: 'Foreign Intelligence',
    description: 'HUMINT recruitment attempt targeting two senior propulsion engineers via professional networking platform. Suspicious contact made by individual using cover identity.',
    probability: 'High',
    impact: 'High',
    riskLevel: 'Critical',
    status: 'Open',
    dateIdentified: '2026-05-12',
    analystNotes: 'Reported to DCSA counterintelligence. Engineers briefed. CI liaison monitoring.',
  },
  {
    id: 'threat-002',
    cpiId: 'cpi-003',
    threatActor: 'Insider Threat — Disgruntled Contractor',
    threatCategory: 'Insider Threat',
    description: 'Anomalous access pattern detected: contractor accessed Phase II schedule documents outside authorized hours on three occasions. No exfiltration confirmed.',
    probability: 'Medium',
    impact: 'High',
    riskLevel: 'High',
    status: 'Monitoring',
    dateIdentified: '2026-04-30',
    analystNotes: 'HR and security management notified. Enhanced audit logging enabled on contractor account.',
  },
  {
    id: 'threat-003',
    cpiId: 'cpi-002',
    threatActor: 'Open Source Aggregation',
    threatCategory: 'Open Source',
    description: 'Two CIPHER contractors posted LinkedIn content referencing "quantum encryption project" and a third referenced the program by name in a conference abstract.',
    probability: 'High',
    impact: 'Medium',
    riskLevel: 'High',
    status: 'Open',
    dateIdentified: '2026-05-20',
    analystNotes: 'OPSEC awareness re-briefing scheduled for all CIPHER personnel. Social media policy enforcement in progress.',
  },
  {
    id: 'threat-004',
    cpiId: 'cpi-005',
    threatActor: 'Advanced Persistent Threat — Nation State',
    threatCategory: 'Cyber',
    description: 'Sustained spear-phishing campaign targeting STARGATE network admins. Two accounts experienced credential stuffing attempts. Perimeter logs show port scans from attributed IP ranges.',
    probability: 'Medium',
    impact: 'High',
    riskLevel: 'High',
    status: 'Monitoring',
    dateIdentified: '2026-05-01',
    analystNotes: 'CISO engaged. MFA enforced on all network admin accounts. CERT notified.',
  },
  {
    id: 'threat-005',
    cpiId: 'cpi-001',
    threatActor: 'Unknown — Physical Surveillance',
    threatCategory: 'Physical',
    description: 'Perimeter security detected repeated loitering and photography near the test facility entrance over a two-week period. Vehicles noted but not identified.',
    probability: 'Low',
    impact: 'Medium',
    riskLevel: 'Medium',
    status: 'Monitoring',
    dateIdentified: '2026-04-15',
    analystNotes: 'Additional CCTV coverage requested. Security patrols increased during test windows.',
  },
  {
    id: 'threat-006',
    cpiId: 'cpi-004',
    threatActor: 'Foreign SIGINT Collection Platform',
    threatCategory: 'Foreign Intelligence',
    description: 'Intelligence community reporting indicates adversary SIGINT assets repositioned to collection posture coinciding with PRISM-7 operational windows.',
    probability: 'Medium',
    impact: 'High',
    riskLevel: 'High',
    status: 'Mitigated',
    dateIdentified: '2026-02-10',
    dateResolved: '2026-03-01',
    analystNotes: 'Emission controls (EMCON) protocol implemented. Collection schedule randomized.',
  },
];

export const MOCK_INDICATORS: OpsecIndicator[] = [
  {
    id: 'ind-001',
    cpiId: 'cpi-001',
    indicatorType: 'Personnel',
    description: 'Engineering staff publishing conference papers that reference propulsion test metrics',
    observable: 'Publicly available academic/technical papers containing performance data that narrows down classified specifications',
    criticality: 'High',
    currentExposure: 'Medium',
    countermeasureApplied: true,
    reviewDate: '2026-06-01',
  },
  {
    id: 'ind-002',
    cpiId: 'cpi-002',
    indicatorType: 'Information',
    description: 'Contractor social media posts referencing program name or quantum encryption work',
    observable: 'LinkedIn, Twitter/X, and professional forums where staff self-identify as working on classified quantum programs',
    criticality: 'High',
    currentExposure: 'High',
    countermeasureApplied: false,
    reviewDate: '2026-05-15',
  },
  {
    id: 'ind-003',
    cpiId: 'cpi-003',
    indicatorType: 'Activity',
    description: 'Travel voucher and per-diem patterns visible in public contracting data correlate with Phase II deployment locations',
    observable: 'USASpending.gov contract modifications and travel-reimbursement codes reference field locations',
    criticality: 'Critical',
    currentExposure: 'High',
    countermeasureApplied: false,
    reviewDate: '2026-05-20',
  },
  {
    id: 'ind-004',
    cpiId: 'cpi-005',
    indicatorType: 'Cyber',
    description: 'Network device procurement records filed under unclassified purchase orders reveal architecture details',
    observable: 'Hardware model numbers and quantities in public procurement filings allow inference of network topology',
    criticality: 'Medium',
    currentExposure: 'Low',
    countermeasureApplied: true,
    reviewDate: '2026-07-01',
  },
  {
    id: 'ind-005',
    cpiId: 'cpi-001',
    indicatorType: 'Physical',
    description: 'Test-facility operational tempo visible from public access road — vehicle flow and lighting patterns',
    observable: 'Predictable increases in vehicle traffic, overnight lighting, and delivery activity before and after propulsion test windows',
    criticality: 'High',
    currentExposure: 'Medium',
    countermeasureApplied: true,
    reviewDate: '2026-06-15',
  },
  {
    id: 'ind-006',
    cpiId: 'cpi-004',
    indicatorType: 'Cyber',
    description: 'SIGINT collection windows correlate with predictable operational schedule',
    observable: 'Emission patterns and collection activity follow a consistent schedule observable by adversary repositioning assets',
    criticality: 'Critical',
    currentExposure: 'Mitigated',
    countermeasureApplied: true,
    reviewDate: '2026-08-01',
  },
];

export const MOCK_COUNTERMEASURES: Countermeasure[] = [
  {
    id: 'cm-001',
    linkedIndicatorId: 'ind-001',
    linkedCpiId: 'cpi-001',
    type: 'Administrative',
    title: 'Pre-Publication Review Process',
    description: 'All technical papers, conference abstracts, and presentations by cleared personnel must undergo FSO/program security review 60 days prior to submission.',
    owner: 'FSO / Program Security Manager',
    implementationDate: '2026-01-15',
    effectiveness: 'High',
    status: 'Active',
    reviewDate: '2027-01-15',
  },
  {
    id: 'cm-002',
    linkedIndicatorId: 'ind-002',
    linkedCpiId: 'cpi-002',
    type: 'Personnel',
    title: 'Social Media OPSEC Awareness Briefing',
    description: 'Mandatory annual social media briefing covering prohibited disclosures, profile scrubbing procedures, and reporting requirements. Acknowledgment form required.',
    owner: 'Security Education Officer',
    implementationDate: '2026-02-01',
    effectiveness: 'Medium',
    status: 'Active',
    reviewDate: '2027-02-01',
  },
  {
    id: 'cm-003',
    linkedIndicatorId: 'ind-003',
    linkedCpiId: 'cpi-003',
    type: 'Administrative',
    title: 'Travel Voucher Aggregation Policy',
    description: 'All field deployment travel reimbursements bundled under consolidated contract line items. Location codes abstracted to prevent pattern analysis from public contract data.',
    owner: 'Contracts / Program Manager',
    implementationDate: '2026-03-10',
    effectiveness: 'High',
    status: 'Pending',
    reviewDate: '2026-09-10',
  },
  {
    id: 'cm-004',
    linkedIndicatorId: 'ind-004',
    linkedCpiId: 'cpi-005',
    type: 'Administrative',
    title: 'Hardware Procurement Bundling',
    description: 'Classified network hardware procured through consolidated purchase orders with generic line-item descriptions to prevent inference of architecture from procurement records.',
    owner: 'Procurement / Security',
    implementationDate: '2025-11-01',
    effectiveness: 'Medium',
    status: 'Active',
    reviewDate: '2026-11-01',
  },
  {
    id: 'cm-005',
    linkedIndicatorId: 'ind-005',
    linkedCpiId: 'cpi-001',
    type: 'Physical',
    title: 'Operational Pattern Randomization',
    description: 'Test window scheduling randomized within approved maintenance periods. Vehicle routing and access gate usage varied. Non-sensitive activity conducted to provide cover for operational periods.',
    owner: 'Facility Security / Test Operations',
    implementationDate: '2026-04-01',
    effectiveness: 'Medium',
    status: 'Active',
    reviewDate: '2026-10-01',
  },
  {
    id: 'cm-006',
    linkedIndicatorId: 'ind-006',
    linkedCpiId: 'cpi-004',
    type: 'Technical',
    title: 'EMCON Protocol — Random Schedule Offset',
    description: 'Emissions control protocol implemented. Collection schedule randomized within ±72-hour windows. Decoy emission profiles generated during non-operational periods.',
    owner: 'Mission Systems / OPSEC Officer',
    implementationDate: '2026-03-01',
    effectiveness: 'High',
    status: 'Active',
    reviewDate: '2026-09-01',
  },
];
